version: '3.6'
services:
    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
    php-fpm:
        build: docker/php
        volumes:
            - './:/usr/share/nginx/html'
    composer:
        image: 'composer:1.8'
        command: install
        volumes:
            - './:/app'
    mariadb:
        image: 'mariadb:10.4.13'
        environment:
            - MYSQL_DATABASE=crm_ipssi
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
