<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvxt6MC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvxt6MC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTvxt6MC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTvxt6MC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTvxt6MC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tvxt6MC',
    'container.build_id' => '10c4ce90',
    'container.build_time' => 1595173321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvxt6MC');
