<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container94EwfED\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container94EwfED/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container94EwfED.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container94EwfED\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container94EwfED\App_KernelDevDebugContainer([
    'container.build_hash' => '94EwfED',
    'container.build_id' => '1e15dd73',
    'container.build_time' => 1595172061,
], __DIR__.\DIRECTORY_SEPARATOR.'Container94EwfED');
